### PR TITLE
Use Alien::HDF4 in PDLA::IO::HDF build

### PR DESCRIPTION
**Pull request by mohawk2**

### CODE REVIEW

**Comment by zmughal** [comment]
Could you add `Alien::HDF4` to the `appveyor.yml` as well?

**Comment by mohawk2** [comment]
Instead I've been bold and added it as a `CONFIGURE_REQUIRES` dep. That'll mean wanting to run it through Travis again as well as Appveyor.

**Comment by zmughal** [comment]
Looks good.

We will need to return to why the `dmake test` target fails in Appveyor because failing at the build stage will mask any failures in all our other changes. A little worrying, no?

**Merge**: _Aye_

**Comment by mohawk2** [comment]
It's an issue but it's probably my fault on some level. I have dmake available here for fast dev when we reach that stage. Merging.

**Pull request merged**
