### PR TITLE
Use Alien::Proj4 from CPAN

### PR DESCRIPTION
**Pull request by shawnlaffan**
A few items remain for consideration, so this PR is WIP at this stage.

- [x] The code currently builds the two modules by default if Alien::Proj4 is installed (it ignores %PDLA::Config settings).
- [x] Alien::Proj4 should perhaps be added to the Makefile.PL as recommends or suggests.  That will become moot once they are separated into their own distros, though.  
- [ ] Need to detect when a user has a system install of Proj4 that does not provide headers.  In these cases we should recommend a share install.  Or perhaps Alien::Proj4 should probe for this and do a share install.  

Edit:  This needs some recent changes to Alien::Proj4 to work.  Relevant PR in PDLPorters/Alien-Proj4#7

### CODE REVIEW

**Comment by mohawk2** [comment]
You'll see I've updated this past my renaming of `Lib` to `Libtmp`, plus a bit of cleanup. How does it look to you now?

**Comment by mohawk2** [comment]
By the way, one of the `.pd` files still uses `default_inc`, that will need updating. Thoughts?

**Comment by mohawk2** [comment]
Thanks for the extra commits! Please note I've added one to it, as well as rebasing it against current master - you changed the MANIFEST entry for `Rest.pm` to `Lib` from `lib`, which isn't right.

**Comment by mohawk2** [comment]
Thanks for the further commits! Please could you do `git pull --rebase` rather than just `git pull`? The latter creates incredibly confusing history :-)

**Comment by mohawk2** [comment]
I've done a force-push which includes your most recent commit. In order to avoid further confusion, I'm going to merge this. I'm then going to split this out into a separate repo, watch this space!

**Comment by shawnlaffan** [comment]
Thanks.  A separate repo will make things simpler.  

I'll get to it again tomorrow (my time), but I'll need suggestions for where the PDL namespace is coming from in the build (per my comment in 33c5a2623b564bdcd832d0e7a43ac96f855e0c68).

**Comment by mohawk2** [comment]
I saw that one myself. My diagnosis isn't what you're saying, but just that the two Proj4 depending things also depend on each other, or at least the "Transform" one depends on the "GIS" one. I'll fix it up in the separate repo. The "Transform::Proj4" one also depends on the "Transform" module which will want splitting out too, though that can wait since in the first instance we can just dep on "::Transform", even though that pulls in all of "::Rest" for now.

Thanks for this awesome work!

**Comment by mohawk2** [comment]
...and now you're a collaborator on the new pdla-gis repo! It all seemed to work with a couple of tweaks, so I released it. It deps on PDLA::Transform, which is in ::Rest for now.

Things it still needs: CI, if you're interested :-)

**Comment by mohawk2** [comment]
Now there's a separated ::Transform, so one can just install ::GIS and get just that and ::Core. On reflection, I think ::GIS wasn't the ideal name, because there could be other GIS modules - those ones are just the Proj4 ones. We can rename it if it becomes useful.

**Comment by shawnlaffan** [comment]
Thanks.  

I suspect the code will not be widely used, as projections are also handled by Geo::Proj and Geo::GDAL::FFI.  It's useful to have hived them off, though.

**Pull request merged**
